FROM quay.io/fedora/fedora:latest
#FROM registry.access.redhat.com/ubi8/ubi:latest

LABEL Author="Daniel Abreu"
LABEL Email="daniel@deabreu.co.za"

# Install requirements.
RUN dnf makecache --timer \
  && dnf -y install initscripts \
  && dnf -y update \
  && dnf -y install \
  wget \
  gcc \
  git \
  unzip \
  curl \
  ansible && dnf clean all

# Create a folder
RUN mkdir tkn-runner-ansible
WORKDIR /tkn-runner-ansible


# Download the latest runner package

# add over the start.sh script

# Add ENV to be pass to shell script
ENV RUNNER_TOKEN=SECRET
ENV REPO_URL=REPO

# set the entrypoint to the start.sh script
ENTRYPOINT [ "/bin/bash" ]
