FROM quay.io/fedora/fedora:latest

LABEL Author="Daniel Abreu"
LABEL Email="daniel@deabreu.co.za"

# Install requirements.
RUN dnf makecache --timer \
  && dnf -y install initscripts \
  && dnf -y update \
  && dnf -y install \
  wget \
  git \
  unzip \
  curl \
  ansible && dnf clean all

# Create a folder
RUN mkdir runner
WORKDIR /runner


# Download the latest runner package

# add over the start.sh script

# Add ENV to be pass to shell script
ENV API_TOKEN=SECRET
ENV API_URL=REPO

# set the entrypoint to the start.sh script
ENTRYPOINT [ "/bin/bash" ]