FROM fedora:latest

RUN dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y \
&& dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y \
&& dnf repolist all \
&& dnf update -y \
&& dnf install vlc -y \
&& dnf clean all -y

ENTRYPOINT [ "/bin/bash" ]